/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminCreateRunner } from '../models';
// @ts-ignore
import type { AdminRunner } from '../models';
// @ts-ignore
import type { Box } from '../models';
// @ts-ignore
import type { CreateRunnerResponse } from '../models';
// @ts-ignore
import type { InfrastructureLogs } from '../models';
// @ts-ignore
import type { InfrastructureLogsAccessDto } from '../models';
// @ts-ignore
import type { PaginatedLogs } from '../models';
/**
 * AdminApi - axios parameter creator
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check infrastructure log access
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminCheckInfrastructureLogsAccess: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/infrastructure-logs/access`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create runner
         * @param {AdminCreateRunner} adminCreateRunner 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminCreateRunner: async (adminCreateRunner: AdminCreateRunner, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminCreateRunner' is not null or undefined
            assertParamExists('adminCreateRunner', 'adminCreateRunner', adminCreateRunner)
            const localVarPath = `/admin/runners`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminCreateRunner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete runner
         * @param {string} id Runner ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminDeleteRunner: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminDeleteRunner', 'id', id)
            const localVarPath = `/admin/runners/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get runner by ID
         * @param {string} id Runner ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetRunnerById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminGetRunnerById', 'id', id)
            const localVarPath = `/admin/runners/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all runners
         * @param {string} [regionId] Filter runners by region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListRunners: async (regionId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/runners`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (regionId !== undefined) {
                localVarQueryParameter['regionId'] = regionId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Recover box from error state as an admin
         * @param {string} boxId ID of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRecoverBox: async (boxId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('adminRecoverBox', 'boxId', boxId)
            const localVarPath = `/admin/box/{boxId}/recover`
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search infrastructure fallback logs
         * @param {Date} from 
         * @param {Date} to 
         * @param {AdminSearchInfrastructureLogsSourceEnum} [source] 
         * @param {string} [search] Case-sensitive literal phrase to find in a log message
         * @param {number} [limit] 
         * @param {string} [nextToken] Opaque CloudWatch pagination cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSearchInfrastructureLogs: async (from: Date, to: Date, source?: AdminSearchInfrastructureLogsSourceEnum, search?: string, limit?: number, nextToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('adminSearchInfrastructureLogs', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('adminSearchInfrastructureLogs', 'to', to)
            const localVarPath = `/admin/infrastructure-logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (nextToken !== undefined) {
                localVarQueryParameter['nextToken'] = nextToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search allowlisted platform OTLP logs
         * @param {Date} from Start of time range (ISO 8601)
         * @param {Date} to End of time range (ISO 8601)
         * @param {number} [page] Page number (1-indexed)
         * @param {number} [limit] Number of items per page
         * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
         * @param {string} [search] Case-insensitive text search in the log body
         * @param {AdminSearchPlatformLogsSourceEnum} [source] 
         * @param {string} [boxId] Exact Box ID. Required when source is box.
         * @param {string} [traceId] Exact OpenTelemetry trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSearchPlatformLogs: async (from: Date, to: Date, page?: number, limit?: number, severities?: Array<string>, search?: string, source?: AdminSearchPlatformLogsSourceEnum, boxId?: string, traceId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('adminSearchPlatformLogs', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('adminSearchPlatformLogs', 'to', to)
            const localVarPath = `/admin/infrastructure-logs/platform`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (severities) {
                localVarQueryParameter['severities'] = severities;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            if (boxId !== undefined) {
                localVarQueryParameter['boxId'] = boxId;
            }

            if (traceId !== undefined) {
                localVarQueryParameter['traceId'] = traceId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update runner scheduling status
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminUpdateRunnerScheduling: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminUpdateRunnerScheduling', 'id', id)
            const localVarPath = `/admin/runners/{id}/scheduling`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Check infrastructure log access
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminCheckInfrastructureLogsAccess(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InfrastructureLogsAccessDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminCheckInfrastructureLogsAccess(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminCheckInfrastructureLogsAccess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create runner
         * @param {AdminCreateRunner} adminCreateRunner 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminCreateRunner(adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateRunnerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminCreateRunner(adminCreateRunner, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminCreateRunner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete runner
         * @param {string} id Runner ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminDeleteRunner(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminDeleteRunner(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminDeleteRunner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get runner by ID
         * @param {string} id Runner ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetRunnerById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminRunner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminGetRunnerById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminGetRunnerById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all runners
         * @param {string} [regionId] Filter runners by region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListRunners(regionId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AdminRunner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListRunners(regionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListRunners']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Recover box from error state as an admin
         * @param {string} boxId ID of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminRecoverBox(boxId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Box>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminRecoverBox(boxId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminRecoverBox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search infrastructure fallback logs
         * @param {Date} from 
         * @param {Date} to 
         * @param {AdminSearchInfrastructureLogsSourceEnum} [source] 
         * @param {string} [search] Case-sensitive literal phrase to find in a log message
         * @param {number} [limit] 
         * @param {string} [nextToken] Opaque CloudWatch pagination cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminSearchInfrastructureLogs(from: Date, to: Date, source?: AdminSearchInfrastructureLogsSourceEnum, search?: string, limit?: number, nextToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InfrastructureLogs>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminSearchInfrastructureLogs(from, to, source, search, limit, nextToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminSearchInfrastructureLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search allowlisted platform OTLP logs
         * @param {Date} from Start of time range (ISO 8601)
         * @param {Date} to End of time range (ISO 8601)
         * @param {number} [page] Page number (1-indexed)
         * @param {number} [limit] Number of items per page
         * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
         * @param {string} [search] Case-insensitive text search in the log body
         * @param {AdminSearchPlatformLogsSourceEnum} [source] 
         * @param {string} [boxId] Exact Box ID. Required when source is box.
         * @param {string} [traceId] Exact OpenTelemetry trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminSearchPlatformLogs(from: Date, to: Date, page?: number, limit?: number, severities?: Array<string>, search?: string, source?: AdminSearchPlatformLogsSourceEnum, boxId?: string, traceId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedLogs>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminSearchPlatformLogs(from, to, page, limit, severities, search, source, boxId, traceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminSearchPlatformLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update runner scheduling status
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminUpdateRunnerScheduling(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminUpdateRunnerScheduling(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminUpdateRunnerScheduling']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * 
         * @summary Check infrastructure log access
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminCheckInfrastructureLogsAccess(options?: RawAxiosRequestConfig): AxiosPromise<InfrastructureLogsAccessDto> {
            return localVarFp.adminCheckInfrastructureLogsAccess(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create runner
         * @param {AdminCreateRunner} adminCreateRunner 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminCreateRunner(adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig): AxiosPromise<CreateRunnerResponse> {
            return localVarFp.adminCreateRunner(adminCreateRunner, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete runner
         * @param {string} id Runner ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminDeleteRunner(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.adminDeleteRunner(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get runner by ID
         * @param {string} id Runner ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetRunnerById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<AdminRunner> {
            return localVarFp.adminGetRunnerById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all runners
         * @param {string} [regionId] Filter runners by region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListRunners(regionId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AdminRunner>> {
            return localVarFp.adminListRunners(regionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Recover box from error state as an admin
         * @param {string} boxId ID of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRecoverBox(boxId: string, options?: RawAxiosRequestConfig): AxiosPromise<Box> {
            return localVarFp.adminRecoverBox(boxId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search infrastructure fallback logs
         * @param {Date} from 
         * @param {Date} to 
         * @param {AdminSearchInfrastructureLogsSourceEnum} [source] 
         * @param {string} [search] Case-sensitive literal phrase to find in a log message
         * @param {number} [limit] 
         * @param {string} [nextToken] Opaque CloudWatch pagination cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSearchInfrastructureLogs(from: Date, to: Date, source?: AdminSearchInfrastructureLogsSourceEnum, search?: string, limit?: number, nextToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<InfrastructureLogs> {
            return localVarFp.adminSearchInfrastructureLogs(from, to, source, search, limit, nextToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search allowlisted platform OTLP logs
         * @param {Date} from Start of time range (ISO 8601)
         * @param {Date} to End of time range (ISO 8601)
         * @param {number} [page] Page number (1-indexed)
         * @param {number} [limit] Number of items per page
         * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
         * @param {string} [search] Case-insensitive text search in the log body
         * @param {AdminSearchPlatformLogsSourceEnum} [source] 
         * @param {string} [boxId] Exact Box ID. Required when source is box.
         * @param {string} [traceId] Exact OpenTelemetry trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSearchPlatformLogs(from: Date, to: Date, page?: number, limit?: number, severities?: Array<string>, search?: string, source?: AdminSearchPlatformLogsSourceEnum, boxId?: string, traceId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedLogs> {
            return localVarFp.adminSearchPlatformLogs(from, to, page, limit, severities, search, source, boxId, traceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update runner scheduling status
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminUpdateRunnerScheduling(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.adminUpdateRunnerScheduling(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminApi - object-oriented interface
 */
export class AdminApi extends BaseAPI {
    /**
     * 
     * @summary Check infrastructure log access
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminCheckInfrastructureLogsAccess(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminCheckInfrastructureLogsAccess(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create runner
     * @param {AdminCreateRunner} adminCreateRunner 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminCreateRunner(adminCreateRunner: AdminCreateRunner, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminCreateRunner(adminCreateRunner, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete runner
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminDeleteRunner(id: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminDeleteRunner(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get runner by ID
     * @param {string} id Runner ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminGetRunnerById(id: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminGetRunnerById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all runners
     * @param {string} [regionId] Filter runners by region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListRunners(regionId?: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListRunners(regionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Recover box from error state as an admin
     * @param {string} boxId ID of the box
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminRecoverBox(boxId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminRecoverBox(boxId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search infrastructure fallback logs
     * @param {Date} from 
     * @param {Date} to 
     * @param {AdminSearchInfrastructureLogsSourceEnum} [source] 
     * @param {string} [search] Case-sensitive literal phrase to find in a log message
     * @param {number} [limit] 
     * @param {string} [nextToken] Opaque CloudWatch pagination cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminSearchInfrastructureLogs(from: Date, to: Date, source?: AdminSearchInfrastructureLogsSourceEnum, search?: string, limit?: number, nextToken?: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminSearchInfrastructureLogs(from, to, source, search, limit, nextToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search allowlisted platform OTLP logs
     * @param {Date} from Start of time range (ISO 8601)
     * @param {Date} to End of time range (ISO 8601)
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [limit] Number of items per page
     * @param {Array<string>} [severities] Filter by severity levels (DEBUG, INFO, WARN, ERROR)
     * @param {string} [search] Case-insensitive text search in the log body
     * @param {AdminSearchPlatformLogsSourceEnum} [source] 
     * @param {string} [boxId] Exact Box ID. Required when source is box.
     * @param {string} [traceId] Exact OpenTelemetry trace ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminSearchPlatformLogs(from: Date, to: Date, page?: number, limit?: number, severities?: Array<string>, search?: string, source?: AdminSearchPlatformLogsSourceEnum, boxId?: string, traceId?: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminSearchPlatformLogs(from, to, page, limit, severities, search, source, boxId, traceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update runner scheduling status
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminUpdateRunnerScheduling(id: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminUpdateRunnerScheduling(id, options).then((request) => request(this.axios, this.basePath));
    }
}

export const AdminSearchInfrastructureLogsSourceEnum = {
    RUNNER: 'runner',
    COLLECTOR: 'collector',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;
export type AdminSearchInfrastructureLogsSourceEnum = typeof AdminSearchInfrastructureLogsSourceEnum[keyof typeof AdminSearchInfrastructureLogsSourceEnum];
export const AdminSearchPlatformLogsSourceEnum = {
    API: 'api',
    WORKER: 'worker',
    RUNNER: 'runner',
    BOX: 'box',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;
export type AdminSearchPlatformLogsSourceEnum = typeof AdminSearchPlatformLogsSourceEnum[keyof typeof AdminSearchPlatformLogsSourceEnum];
